export const CREATE_FIELD = 'CREATE_FIELD';
export const REMOVE_FIELD = 'REMOVE_FIELD';
export const UPDATE_FIELD_TYPE = 'UPDATE_FIELD_TYPE';
export const UPDATE_FIELD_VALUE = 'UPDATE_FIELD_VALUE';
export const CREATE_FORM = 'CREATE_FORM';
export const UPDATE_FIELD_ERROR = 'UPDATE_FIELD_ERROR';
export const CLEAR_ALL_FIELDS = 'CLEAR_ALL_FIELDS';
